db.current-url=${db.url.dev}

# MyBatis
mybatis.mapper-locations=classpath:mappers/**/*.xml
mybatis.config-location=classpath:mybatis-config-mysql.xml

# log file
log.config.path=./logs
logging.level.root=INFO
#logging.level.root=DEBUG
#logging.level.org.springframework=DEBUG
