spring.config.import=optional:classpath:env.properties

server.port=${db.port}
spring.application.name=${project.name}

spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=${db.username}
spring.datasource.password=${db.password}
spring.datasource.url=${db.current-url}

spring.profiles.active=dev